[package]
name = "aoc_dijsktra"
authors = ["Rareș Cosma <rares@getbetter.ro>"]
version = "0.1.0"
edition = "2021"

[dependencies]
ahash.workspace = true
hashbrown.workspace = true
lazy_static.workspace = true
num-traits.workspace = true
